name: pr-test.yml

on:
  workflow_dispatch:
  pull_request:

permissions:
  contents: read
  pull-requests: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: test1234
          MYSQL_DATABASE: testdb
          MYSQL_USER: testuser
          MYSQL_PASSWORD: test1234
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

      redis:
        image: redis:6.2
        ports:
          - 6379:6379
        options: >-
          --health-cmd="redis-cli ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      RDS_URL: localhost
      MYSQL_PORT: 3306
      MYSQL_DBNAME: testdb
      MYSQL_USERNAME: testuser
      MYSQL_PASSWORD: test1234
      JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
      REDIS_HOST: localhost
      REDIS_PORT: 6379
      SERVER_PORT: 8080

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: setup jdk
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Run tests
        run: ./gradlew test